#!/usr/bin/env python3
"""AX 2012 -> ClickHouse star schema. Four source tables, nothing else.

    ~/clickhouse client --port 9010 --queries-file ch_schema.sql   # once
    MSSQL_HOST=... MSSQL_USER=... MSSQL_PASS=... MSSQL_DB=... python3 ax_load.py
    python3 ax_load.py --demo      # ClickHouse half only, no MSSQL needed

Sources: SALESTABLE, SALESLINE, CUSTTABLE, CUSTTRANS.
Targets: dim_customer, dim_item, dim_currency, fact_sales, fact_cust_trans.
         dim_date and dim_status are generated by ch_schema.sql, not loaded.

ponytail: no staging layer. Every dimension and fact reads straight from MSSQL
into its final table -- a staging copy would double the storage and the load time
to serve an INSERT..SELECT that the source query already does.

ponytail: pymssql, not pyodbc as etl.py uses, because this server only offers
TLS 1.0 and needs TDS 7.0 (see schema_dump.py). SALESLINE is chunked on the way
in; the rest are small enough for one POST.
"""
import os
import sys
from datetime import datetime

import etl  # ch(), insert()

TDSVER = "7.0"

# ponytail: version = MAX(modified, created), not MODIFIEDDATETIME. AX leaves
# MODIFIEDDATETIME at 1900 on rows never edited since insert, and `> watermark`
# would then skip them forever on the second run.
VERSION = "(SELECT MAX(v) FROM (VALUES (t.MODIFIEDDATETIME), (t.CREATEDDATETIME)) AS x(v))"

# --- dimensions -------------------------------------------------------------

# CUSTTABLE holds a PARTY pointer, not a name; DIRPARTYTABLE is the 1:1 party
# record it points at, so folding the name in cannot fan the grain out.
DIM_CUSTOMER = """
SELECT t.DATAAREAID, t.ACCOUNTNUM, p.NAME, p.NAMEALIAS, t.CUSTGROUP, t.CURRENCY,
       t.PAYMTERMID, t.CREDITMAX, t.BLOCKED, t.INVOICEACCOUNT, t.RECID,
       (SELECT MAX(v) FROM (VALUES (t.MODIFIEDDATETIME), (p.MODIFIEDDATETIME)) AS x(v))
FROM CUSTTABLE t JOIN DIRPARTYTABLE p ON p.RECID = t.PARTY
WHERE (SELECT MAX(v) FROM (VALUES (t.MODIFIEDDATETIME), (p.MODIFIEDDATETIME)) AS x(v)) > %s
"""

# No product master in scope, so the item dimension is distilled from the lines.
# MAX(NAME) per item picks one name where history disagrees.
# The version expression is a subquery, and SQL Server refuses to aggregate over
# one — so it is resolved in a derived table first, then aggregated.
DIM_ITEM = f"""
SELECT DATAAREAID, ITEMID, MAX(NAME), MAX(ver)
FROM (SELECT t.DATAAREAID, t.ITEMID, t.NAME, {VERSION} AS ver
      FROM SALESLINE t WHERE t.ITEMID <> '') s
WHERE ver > %s
GROUP BY DATAAREAID, ITEMID
"""

# Every currency code any of the four tables actually uses.
DIM_CURRENCY = """
SELECT code, GETDATE() FROM (
    SELECT DISTINCT CURRENCY     AS code FROM CUSTTABLE  WHERE CURRENCY     <> ''
    UNION SELECT DISTINCT CURRENCYCODE   FROM SALESTABLE WHERE CURRENCYCODE <> ''
    UNION SELECT DISTINCT CURRENCYCODE   FROM SALESLINE  WHERE CURRENCYCODE <> ''
    UNION SELECT DISTINCT CURRENCYCODE   FROM CUSTTRANS  WHERE CURRENCYCODE <> ''
) c
"""

# --- facts ------------------------------------------------------------------

# SALESLINE is the grain; SALESTABLE contributes the header attributes that
# belong on every line (order name, document status, order date).
FACT_SALES = f"""
SELECT t.DATAAREAID, t.SALESID, t.LINENUM, t.CUSTACCOUNT, t.ITEMID,
       t.CURRENCYCODE, CONVERT(date, h.CREATEDDATETIME),
       CONVERT(date, t.SHIPPINGDATEREQUESTED), t.SALESSTATUS,
       ISNULL(h.DOCUMENTSTATUS, 0), t.QTYORDERED, t.SALESPRICE, t.COSTPRICE,
       t.LINEAMOUNT, t.LINEDISC, ISNULL(h.SALESNAME, ''), t.INVENTTRANSID,
       t.RECID, {VERSION}
FROM SALESLINE t
LEFT JOIN SALESTABLE h ON h.SALESID = t.SALESID AND h.DATAAREAID = t.DATAAREAID
WHERE {VERSION} > %s
"""

FACT_CUST_TRANS = f"""
SELECT t.DATAAREAID, t.ACCOUNTNUM, t.CURRENCYCODE, CONVERT(date, t.TRANSDATE),
       CONVERT(date, t.DUEDATE), t.TRANSTYPE, t.AMOUNTCUR, t.AMOUNTMST,
       t.SETTLEAMOUNTCUR, t.SETTLEAMOUNTMST, t.VOUCHER, t.INVOICE, t.TXT,
       CONVERT(date, t.CLOSED), t.RECID, {VERSION}
FROM CUSTTRANS t
WHERE {VERSION} > %s
"""

COLS = {
    "dim_customer": "data_area customer_id name name_alias group_code currency "
                    "payment_terms credit_limit blocked invoice_account recid "
                    "modified".split(),
    "dim_item": "data_area item_id item_name modified".split(),
    "dim_currency": "currency_code modified".split(),
    "fact_sales": "data_area sales_id line_num cust_account item_id currency "
                  "order_date ship_date sales_status document_status qty_ordered "
                  "sales_price cost_price line_amount line_disc sales_name "
                  "invent_trans_id recid modified".split(),
    "fact_cust_trans": "data_area cust_account currency trans_date due_date "
                       "trans_type amount_cur amount_mst settle_cur settle_mst "
                       "voucher invoice txt closed recid modified".split(),
}

# dim_currency has no usable watermark (a DISTINCT has no row timestamp), so it
# reloads in full. It is a few dozen rows.
FULL_RELOAD = {"dim_currency"}

EPOCH = datetime(1900, 1, 1)  # AX's own empty date, and DateTime64's floor


def watermark(table: str) -> datetime:
    """Where the last run stopped, read from the target — ClickHouse is the only
    thing that knows what it actually holds."""
    ts = etl.ch(f"SELECT max(modified) FROM ax.{table}").strip()
    return EPOCH if ts.startswith(("1900", "1970")) else datetime.fromisoformat(ts)


def connect():
    os.environ.setdefault("TDSVER", TDSVER)
    import pymssql

    return pymssql.connect(
        server=os.environ["MSSQL_HOST"],
        user=os.environ["MSSQL_USER"],
        password=os.environ["MSSQL_PASS"],
        database=os.environ["MSSQL_DB"],
        port=os.environ.get("MSSQL_PORT", "1433"),
    )


def load_table(conn, table: str, sql: str, since: datetime | None) -> int:
    cur = conn.cursor()
    cur.execute(sql, (since,)) if since else cur.execute(sql)
    rows = cur.fetchall()
    # SALESLINE is 186k rows; one POST of that is a 70MB body. Chunk it.
    for i in range(0, len(rows), etl.CHUNK):
        etl.insert([dict(zip(COLS[table], r)) for r in rows[i:i + etl.CHUNK]], f"ax.{table}")
    return len(rows)


def load() -> None:
    conn = connect()
    # Dimensions before facts: a fact row landing first would point at a
    # dimension key that isn't there yet.
    for table, sql in (("dim_customer", DIM_CUSTOMER),
                       ("dim_item", DIM_ITEM),
                       ("dim_currency", DIM_CURRENCY),
                       ("fact_sales", FACT_SALES),
                       ("fact_cust_trans", FACT_CUST_TRANS)):
        since = None if table in FULL_RELOAD else watermark(table)
        n = load_table(conn, table, sql, since)
        print(f"{table}: {n:,} rows"
              + (" (full reload)" if since is None else f" changed since {since}"))
    conn.close()


def demo() -> None:
    """ClickHouse half only: proves the insert path and that a reloaded row
    replaces rather than duplicates."""
    etl.ch("TRUNCATE TABLE ax.dim_customer")
    row = dict(zip(COLS["dim_customer"], [
        "usmf", "C1", "Contoso", "", "10", "USD", "N030",
        "1000.0000000000000000", 0, "C1", 5637144576, "2024-01-01 10:00:00.000"]))
    etl.insert([row], "ax.dim_customer")
    etl.insert([{**row, "name": "Contoso Ltd", "modified": "2024-01-02 10:00:00.000"}],
               "ax.dim_customer")

    n = int(etl.ch("SELECT count() FROM ax.dim_customer").strip())
    assert n == 2, f"both versions land as separate parts, got {n}"
    name = etl.ch("SELECT name FROM ax.dim_customer FINAL").strip()
    assert name == "Contoso Ltd", f"FINAL keeps the newest version, got {name}"
    assert watermark("dim_customer") == datetime(2024, 1, 2, 10, 0)
    etl.ch("TRUNCATE TABLE ax.dim_customer")
    print("ok")


if __name__ == "__main__":
    demo() if "--demo" in sys.argv else load()
